[default]
extend-ignore-re = ["Groth","groth","wee","Wee","PRIMITVE","satifies","Substraction","substraction","coeffient","cofficient","Supress","elemnts"]
files = ["!*.lock", "!target/*","!doc/CHANGELOG.md"]
